name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci
          npm --prefix tasks/ReplaceTokensV3 ci
          npm --prefix tasks/ReplaceTokensV4 ci
          npm --prefix tasks/ReplaceTokensV5 ci

      - name: Check code format
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Package
        run: npm run package